# Generated by Django 2.1 on 2019-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_default_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_catagory',
            field=models.IntegerField(choices=[(1, 'FOOD'), (2, 'RENT'), (3, 'SALARY')], default=0),
        ),
    ]
