# Generated by Django 2.1 on 2019-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190416_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
