# Generated by Django 2.1 on 2019-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190424_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
